### ISSUE TITLE
Text in the transcript_search index field (compound objects) does not match the text in the order it appears in the compound parts

### ISSUE THREAD

**Issue by jrynhart** [dulibrarytech/digitaldu-backend-transcripts#1]
There may be parts of the transcript missing from transcript_search, and some parts are missing transcript data

Part 1 transcript does not appear in transcript_search
http://lib-es04-vlp.du.edu:9200/repo_public/_doc/6c18191f-6162-4835-9a42-5b6a54471d52

Part 2 has no transcript, but it looks like the part 2 text does appear in transcript_search
http://lib-es04-vlp.du.edu:9200/repo_public/_doc/a4268470-8f70-4236-bc84-71185653a2f6

**Comment by freyesdulib** [comment]
These were test records ingested with the original transcript service code.  @scottsalvaggio applied fixes and made optimizations and tested before going live.  The records containing transcripts ingested over the past week look good. i.e. (a32ee5b9-caa4-43b7-9e20-2a4d0b3c6d41 - repo_admin index)  I'll monitor the records closely to make sure there are no other issues.  Thanks.
